// Generated by https://quicktype.io

class CryptoModel {
  String? id;
  String? symbol;
  String? name;
  String? description;
  String? image;
  String? genesisDate;
  double? currentPriceUsd;
  double? currentPriceMxn;

  CryptoModel(
    this.id,
    this.symbol,
    this.name,
    this.description,
    this.image,
    this.genesisDate,
    this.currentPriceUsd,
    this.currentPriceMxn,
  );
}
